AluguelCarro/Controllers/AlugueisController.cs
using AluguelCarro.AcessoDados.Interfaces;
using AluguelCarro.Models;
using AluguelCarro.Models.ViewModels;
using AluguelCarro.Servicos;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace AluguelCarro.Controllers
{
    [Authorize]
    public class AlugueisController : Controller
    {
        private readonly IUsuarioRepositorio _usuarioRepositorio;
        private readonly IContaRepositorio _contaRepositorio;
        private readonly IAluguelRepositorio _aluguelRepositorio;
        private readonly ILogger<AlugueisController> _logger;
        private readonly IEmail _email;
        public AlugueisController(IUsuarioRepositorio usuarioRepositorio, IContaRepositorio contaRepositorio, IAluguelRepositorio aluguelRepositorio, ILogger<AlugueisController> logger, IEmail email)
        {
            _usuarioRepositorio = usuarioRepositorio;
            _contaRepositorio = contaRepositorio;
            _aluguelRepositorio = aluguelRepositorio;
            _logger = logger;
            _email = email;
        }
        public IActionResult Alugar(int carroId, int precoDiaria)
        {
            _logger.LogInformation("Começando o aluguel do carro");

            var aluguel = new AluguelViewModel
            {
                CarroId = carroId,
                PrecoDiaria = precoDiaria
            };
            return View(aluguel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Alugar(AluguelViewModel aluguel)
        {
            if (ModelState.IsValid)
            {
                var usuario = await _usuarioRepositorio.PegarUsuarioLogado(User);
                var saldo =  _contaRepositorio.PegarSaldoPeloId(usuario.Id);

                if (await _aluguelRepositorio.VerificarReserva(usuario.Id, aluguel.CarroId, aluguel.Inicio, aluguel.Fim))
                {
                    _logger.LogInformation("Usuário já possui essa reserva");
                    TempData["Aviso"] = "Você já possui essa reserva";
                    return View(aluguel);
                }
                else if(aluguel.PrecoTotal > saldo)
                {
                    _logger.LogInformation("Saldo insuficiente");
                    TempData["Aviso"] = "Saldo insuficiente";
                    return View(aluguel);
                }
                else
                {
                    Aluguel a = new Aluguel
                    {
                        UsuarioId = usuario.Id,
                        CarroId = aluguel.CarroId,
                        Inicio = aluguel.Inicio,
                        Fim = aluguel.Fim,
                        PrecoTotal = aluguel.PrecoTotal
                    };

                    _logger.LogInformation("Enviando e-mail com detalhes da reserva");
                    string assunto = "reserva concluida com sucesso";

                    string mensagem = string.Format("Seu veículo já o aguarda. Você podera pega-lo dia {0}" +
                        " e devara deveolve-lo dia {1}. o preço será de R${2},00. Divirta-se!!!", aluguel.Inicio, aluguel.Fim, aluguel.PrecoTotal);

                    await _email.EnviarEmail(usuario.Email, assunto, mensagem);

                    await _aluguelRepositorio.Inserir(a);
                    _logger.LogInformation("Reserva feita");

                    _logger.LogInformation("Atualizando saldo usuario");
                    var saldoUsuario = await _contaRepositorio.PegarSaldoPeloUsuarioId(usuario.Id);
                    saldoUsuario.Saldo = saldoUsuario.Saldo - aluguel.PrecoTotal;
                    await _contaRepositorio.Atualizar(saldoUsuario);
                    _logger.LogInformation("Saldo Atualizado");


                    return RedirectToAction("index", "Carros");
                }
            }
            _logger.LogInformation("Informações inválidas");
            return View(aluguel);

        }
    }
}

AluguelCarro/ViewComponents/AluguelViewComponent.cs
using AluguelCarro.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace AluguelCarro.ViewComponents
{
    public class AluguelViewComponent : ViewComponent
    {
        private readonly Contexto _contexto;
        public AluguelViewComponent(Contexto contexto)
        {
            _contexto = contexto;
        }

        public async Task<IViewComponentResult> InvokeAsync(int carroId)
        {
            return View(await _contexto.Carros.FirstOrDefaultAsync(c => c.CarroId == carroId));
        }
    }
}

AluguelCarro/Views/Alugueis/Alugar.cshtml
@model AluguelCarro.Models.ViewModels.AluguelViewModel
@{
    ViewData["Title"] = "Aluguel de carros";
}

@await Component.InvokeAsync("Aluguel", Model.CarroId)

<div class="border border-light rounded shadow col-md-8">
    <div class="container">
        <h3 class="titulo"><i class="fas fa-car fa-lg"></i>Aluguel de veículos</h3>
        <hr />
        @if (TempData["Aviso"] != null)
        {
            <p class="alert alert-warning">@TempData["Aviso"].ToString()</p>
        }


        <div class="row">
            <div class="col-md-8">
                <form asp-action="Alugar">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>

                    <input asp-for="CarroId" type="hidden" />

                    <div class="campos">
                        <div class="form-group">
                            <label asp-for="Inicio" class="control-label"></label>
                            <input asp-for="Inicio" class="form-control form-control-lg datepicker" id="Inicio" />
                            <span asp-validation-for="Inicio" class="text-danger"></span>
                        </div>
                    </div>

                    <div class="campos">
                        <div class="form-group">
                            <label asp-for="Fim" class="control-label"></label>
                            <input asp-for="Fim" class="form-control form-control-lg datepicker" id="Fim" />
                            <span asp-validation-for="Fim" class="text-danger"></span>
                        </div>
                    </div>

                    <div class="campos">
                        <div class="form-group">
                            <label asp-for="PrecoDiaria" class="control-label">Preço da Diária</label>
                            <input asp-for="PrecoDiaria" class="form-control form-control-lg" id="precoDiaria" readonly />
                            <span asp-validation-for="PrecoDiaria" class="text-danger"></span>
                        </div>
                    </div>

                    <div class="campos">
                        <div class="form-group">
                            <label asp-for="PrecoTotal" class="control-label">Preço Total</label>
                            <input asp-for="PrecoTotal" class="form-control form-control-lg" id="precoTotal" readonly />
                            <span asp-validation-for="PrecoTotal" class="text-danger"></span>
                        </div>
                    </div>

                    <div class="form-group botoes">
                        <input type="submit" value="Salvar" class="btn btn-outline-success btn-lg" /> &nbsp;
                        <a asp-action="Index" class="btn btn-link btn-lg">Voltar</a>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}

    <script>
        $(".datepicker").datepicker({
            autoclose: true,
            calendarWeeks: true,
            clearBtn: true,
            todayBtn: true,
            todayHighlight: true,
            format: "dd/mm/yyyy",
            language: "pt-BR"
        })
        $("#Inicio").on('change', function () {
            if (($("#Inicio").val() !== "" && $("#Inicio").val() !== undefined) && ($("#Fim").val() !== "" && $("#Fim").val() !== undefined)) {
                var i = $("#Inicio").val().split("/");
                var inicio = new Date(i[2], i[1], i[0]);
                var f = $("#Fim").val().split("/");
                var fim = new Date(f[2], f[1], f[0]);
                var dias = ((fim - inicio) / 86400) / 1000;
                var precoDiaria = parseInt($("#precoDiaria").val());
                var precoTotal = precoDiaria * dias;

                $("#precoTotal").val(precoTotal);
            }
        });
        $("#Fim").on('change', function () {
            if (($("#Inicio").val() !== "" && $("#Inicio").val() !== undefined) && ($("#Fim").val() !== "" && $("#Fim").val() !== undefined)) {
                var i = $("#Inicio").val().split("/");
                var inicio = new Date(i[2], i[1], i[0]);
                var f = $("#Fim").val().split("/");
                var fim = new Date(f[2], f[1], f[0]);
                var dias = ((fim - inicio) / 86400) / 1000;

                var precoDiaria = parseInt($("#precoDiaria").val());
                var precoTotal = precoDiaria * dias;

                $("#precoTotal").val(precoTotal);
            }
        });
    </script>
}