AluguelCarro/Models/Usuario.cs
using Microsoft.AspNetCore.Identity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace AluguelCarro.Models
{
    public class Usuario : IdentityUser
    {
        public string Nome { get; set; }
        public string CPF { get; set; }
        public string Telefone { get; set; }
        public ICollection<Endereco> Enderecos { get; set; }
        public ICollection<Aluguel> Alugueis { get; set; }
        public Conta Conta { get; set; }
    }
}

AluguelCarro/Models/ViewModels/AtualizarViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace AluguelCarro.Models.ViewModels
{
    public class AtualizarViewModel
    {
        public string Id { get; set; }

        [Required(ErrorMessage = "Campo obrigatório")]
        [StringLength(100, ErrorMessage = "Use menos caracteres")]
        public string Nome { get; set; }

        [Required(ErrorMessage = "Campo obrigatório")]
        public string CPF { get; set; }

        [Required(ErrorMessage = "Campo obrigatório")]
        public string Telefone { get; set; }

        [Required(ErrorMessage = "Campo obrigatório")]
        [StringLength(100, ErrorMessage = "Use menos caracteres")]
        public string NomeUsuario { get; set; }

        [Required(ErrorMessage = "Campo obrigatório")]
        [StringLength(100, ErrorMessage = "Use menos caracteres")]
        [DataType(DataType.EmailAddress, ErrorMessage = "Email inválido")]
        public string Email { get; set; }
    }
}

AluguelCarro/Models/ViewModels/LoginViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace AluguelCarro.Models.ViewModels
{
    public class LoginViewModel
    {
        [Required(ErrorMessage ="Campo obrigatório")]
        [DataType(DataType.EmailAddress, ErrorMessage ="Email inválido")]
        public string Email { get; set; }

        [Required(ErrorMessage = "Campo obrigatório")]
        [DataType(DataType.Password)]
        public string Senha { get; set; }
    }
}

AluguelCarro/Models/ViewModels/RegistroViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace AluguelCarro.Models.ViewModels
{
    public class RegistroViewModel
    {
        [Required(ErrorMessage = "Campo Obrigatório")]
        [StringLength(100, ErrorMessage = "Use menos caracteres")]
        public string Nome { get; set; }

        [Required(ErrorMessage = "Campo Obrigatório")]
        public string CPF { get; set; }

        [Required(ErrorMessage = "Campo Obrigatório")]
        public string Telefone { get; set; }

        [Required(ErrorMessage = "Campo Obrigatório")]
        [StringLength(100, ErrorMessage = "Use menos caracteres")]
        public string NomeUsuario { get; set; }

        [Required(ErrorMessage = "Campo Obrigatório")]
        [StringLength(100, ErrorMessage = "Use menos caracteres")]
        [DataType(DataType.EmailAddress, ErrorMessage = "Email inválido")]
        public string Email { get; set; }

        [Required(ErrorMessage = "Campo Obrigatório")]
        [StringLength(100, ErrorMessage = "Use menos caracteres")]
        [DataType(DataType.Password)]
        public string Senha { get; set; }
    }
}

AluguelCarro/Controllers/EnderecosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using AluguelCarro.Models;
using AluguelCarro.AcessoDados.Interfaces;
using Microsoft.Extensions.Logging;
using Microsoft.AspNetCore.Authorization;

namespace AluguelCarro.Controllers
{
    [Authorize]
    public class EnderecosController : Controller
    {
        private readonly IUsuarioRepositorio _usuarioRepositorio;
        private readonly IEnderecoRepositorio _enderecoRepositorio;
        private readonly ILogger<EnderecosController> _logger;

        public EnderecosController(IUsuarioRepositorio usuarioRepositorio, IEnderecoRepositorio enderecoRepositorio, ILogger<EnderecosController> logger)
        {
            _usuarioRepositorio = usuarioRepositorio;
            _enderecoRepositorio = enderecoRepositorio;
            _logger = logger;
        }


        // GET: Enderecos/Create
        public async Task<IActionResult> Create()
        {
            _logger.LogInformation("Novo endereço");
            var usuario = await _usuarioRepositorio.PegarUsuarioLogado(User);
            var endereco = new Endereco { UsuarioId = usuario.Id };
            return View(endereco);
        }

        // POST: Enderecos/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("EnderecoId,Rua,Numero,Bairro,Cidade,Estado,UsuarioId")] Endereco endereco)
        {
            if (ModelState.IsValid)
            {
                await _enderecoRepositorio.Inserir(endereco);
                _logger.LogInformation("Novo endereço cadastrado");
                return RedirectToAction("Index", "Usuarios");
            }
            _logger.LogError("Erro no cadastro do endereço");
            return View(endereco);
        }

        // GET: Enderecos/Edit/5
        public async Task<IActionResult> Edit(int id)
        {
            _logger.LogInformation("Atualizando endereço");

            var endereco = await _enderecoRepositorio.PegarPeloId(id);
            if (endereco == null)
            {
                _logger.LogError("Endereço não cadastrado");
                return NotFound();
            }
            return View(endereco);
        }

        // POST: Enderecos/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("EnderecoId,Rua,Numero,Bairro,Cidade,Estado,UsuarioId")] Endereco endereco)
        {
            if (id != endereco.EnderecoId)
            {
                _logger.LogError("Endereço não cadastrado");
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                await _enderecoRepositorio.Atualizar(endereco);
                _logger.LogInformation("Endereço atualizado");
                return RedirectToAction("Index", "Usuarios");
            }
            _logger.LogError("Endereço inválido");
            return View(endereco);
        }

        // POST: Enderecos/Delete/5
        [HttpPost]
        public async Task<JsonResult> Delete(int id)
        {
            await _enderecoRepositorio.Excluir(id);
            return Json("Endereço excluído");
        }

    }
}

AluguelCarro/Controllers/UsuariosController.cs
using AluguelCarro.AcessoDados.Interfaces;
using AluguelCarro.Models;
using AluguelCarro.Models.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace AluguelCarro.Controllers
{
    [Authorize]
    public class UsuariosController : Controller
    {
        private readonly IUsuarioRepositorio _usuarioRepositorio;
        private readonly ILogger<UsuariosController> _logger;

        public UsuariosController(IUsuarioRepositorio usuarioRepositorio, ILogger<UsuariosController> logger)
        {
            _usuarioRepositorio = usuarioRepositorio;
            _logger = logger;
        }

        public async Task<IActionResult> Index()
        {
            _logger.LogInformation("Listando informações");
            return View(await _usuarioRepositorio.PegarUsuarioLogado(User));
        }

        [AllowAnonymous]
        public async Task<IActionResult> Registro()
        {
            //deslogar usuario caso esteja logado
            if (User.Identity.IsAuthenticated)
                await _usuarioRepositorio.EfetuarLogOut();

            _logger.LogInformation("Entrando na página de registro");
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [AllowAnonymous]
        public async Task<IActionResult> Registro(RegistroViewModel registro)
        {
            if (ModelState.IsValid)
            {
                var usuario = new Usuario
                {
                    UserName = registro.NomeUsuario,
                    Email = registro.Email,
                    CPF = registro.CPF,
                    Telefone = registro.Telefone,
                    Nome = registro.Nome,
                    PasswordHash = registro.Senha
                };

                _logger.LogInformation("Tetando criar um usuario");
                //status da criação do usuario
                var resultado = await _usuarioRepositorio.SalvarUsuario(usuario, registro.Senha);
               
                //verificando se cadastro esta ok.
                if (resultado.Succeeded)
                {
                    _logger.LogInformation("Novo Usuário criado");
                    _logger.LogInformation("Atribuindo nível de acesso ao usuário");
                    var nivelAcesso = "Cliente";

                    await _usuarioRepositorio.AtribuirNivelAcesso(usuario, nivelAcesso);
                    _logger.LogInformation("Atribuição concluida");

                    _logger.LogInformation("Logando o usuário");
                    await _usuarioRepositorio.EfetuarLogin(usuario, false);
                    _logger.LogInformation("Usuario logado com sucesso");

                    return RedirectToAction("Index", "Usuarios");
                }
                else
                {
                    _logger.LogError("Erros ao criar o usuário");

                    foreach (var erro in resultado.Errors)
                        ModelState.AddModelError("", erro.Description.ToString());
                }
            }

            _logger.LogError("Informações de usuário inválidas");
            return View(registro);
        }

        //action login
        [AllowAnonymous]
        public async Task<IActionResult> Login()
        {
            if (User.Identity.IsAuthenticated)
                await _usuarioRepositorio.EfetuarLogOut();
            
            _logger.LogInformation("Entrando na página de login");
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [AllowAnonymous]
        public async Task<IActionResult> Login(LoginViewModel login)
        {
            if (ModelState.IsValid)
            {
                _logger.LogInformation("Pegando usuario pelo e-mail");
                var usuario = await _usuarioRepositorio.PegarUsuarioPeloEmail(login.Email);
                PasswordHasher<Usuario> passwordHasher = new PasswordHasher<Usuario>();

                if (usuario != null)
                {
                    _logger.LogInformation("Vefificando informações do usuário");
                    if (passwordHasher.VerifyHashedPassword(usuario, usuario.PasswordHash, login.Senha) != PasswordVerificationResult.Failed)
                    {
                        _logger.LogInformation("informações corretas. logando o usuário");
                        await _usuarioRepositorio.EfetuarLogin(usuario, false);

                        return RedirectToAction("Index", "Usuarios");
                    }

                    _logger.LogError("Informações inválidas");
                    ModelState.AddModelError("", "Email e/ou senha inválidos");
                }

                _logger.LogError("Informações inválidas");
                ModelState.AddModelError("", "Email e/ou senha inválidos");

            }

            return View(login);
        }

        public async Task<IActionResult> LogOut()
        {
            await _usuarioRepositorio.EfetuarLogOut();

            return RedirectToAction("Login", "Usuarios");
        }

        //atualizar usuario
        [HttpGet]
        public async Task<IActionResult> Atualizar(string usuarioId)
        {
            _logger.LogInformation("Verificando se o usuáeio existe");
            var usuario = await _usuarioRepositorio.PegarPeloId(usuarioId);

            var atualizarViewModel = new AtualizarViewModel
            {
                Id = usuario.Id,
                Nome = usuario.Nome,
                CPF = usuario.CPF,
                Email = usuario.Email,
                Telefone = usuario.Telefone,
                NomeUsuario = usuario.UserName
            };
            _logger.LogInformation("Atualizar usuário");
            return View(atualizarViewModel);

        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Atualizar(AtualizarViewModel atualizarViewModel)
        {
            if (ModelState.IsValid)
            {
                var usuario = await _usuarioRepositorio.PegarPeloId(atualizarViewModel.Id);

                usuario.Nome = atualizarViewModel.Nome;
                usuario.CPF = atualizarViewModel.CPF;
                usuario.UserName = atualizarViewModel.NomeUsuario;
                usuario.Email = atualizarViewModel.Email;
                usuario.Telefone = atualizarViewModel.Telefone;

                await _usuarioRepositorio.AtualizarUsuario(usuario);
                _logger.LogInformation("Atualizando usuário");

                return RedirectToAction("Index", "Usuarios");

            }
            _logger.LogError("Informações inválidas");

            return View(atualizarViewModel);
        }

    }
}

AluguelCarro/ViewComponents/CarrosAlugadosViewComponent.cs
using AluguelCarro.AcessoDados.Interfaces;
using AluguelCarro.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace AluguelCarro.ViewComponents
{
    public class CarrosAlugadosViewComponent : ViewComponent
    {
        private readonly IUsuarioRepositorio _usuarioRepositorio;
        private readonly Contexto _contexto;
        public CarrosAlugadosViewComponent( IUsuarioRepositorio usuarioRepositorio, Contexto contexto)
        {
            _contexto = contexto;
            _usuarioRepositorio = usuarioRepositorio;
        }

        public async Task<IViewComponentResult> InvokeAsync()
        {
            var usuarioLogado = await _usuarioRepositorio.PegarUsuarioLogado(HttpContext.User);
            return View(await _contexto.Alugueis.Include(a => a.Carro).Where(a => a.UsuarioId == usuarioLogado.Id).ToListAsync());
        }
    }
}

AluguelCarro/ViewComponents/EnderecoViewComponent.cs
using AluguelCarro.AcessoDados.Interfaces;
using AluguelCarro.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace AluguelCarro.ViewComponents
{
    public class EnderecoViewComponent : ViewComponent
    {
        private readonly Contexto _contexto;
        private readonly IUsuarioRepositorio _usuarioRepositorio;
        public EnderecoViewComponent(Contexto contexto, IUsuarioRepositorio usuarioRepositorio)
        {
            _contexto = contexto;
            _usuarioRepositorio = usuarioRepositorio;
        }

        public async Task<IViewComponentResult> InvokeAsync()
        {
            var usuario = await _usuarioRepositorio.PegarUsuarioLogado(HttpContext.User);
            return View(await _contexto.Enderecos.Where(e => e.UsuarioId == usuario.Id).ToListAsync());
        }
    }
}

AluguelCarro/Views/Usuarios/Atualizar.cshtml
@model AluguelCarro.Models.ViewModels.AtualizarViewModel
@{
    ViewData["Title"] = "Atualizar usuário " + Model.NomeUsuario;
}

<div class="border border-light rounded shadow col-md-8">
    <div class="container">
        <h3 class="titulo"><i class="fas fa-user"></i>Atualizar usuário @Model.NomeUsuario</h3>
        <hr />
        <div class="row">
            <div class="col-md-8">
                <form asp-action="Atualizar">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>

                    <input asp-for="Id" type="hidden" />

                    <div class="campos">
                        <div class="form-group">
                            <label asp-for="Nome" class="control-label">Nome</label>
                            <input asp-for="Nome" class="form-control form-control-lg" />
                            <span asp-validation-for="Nome" class="text-danger"></span>
                        </div>
                    </div>

                    <div class="campos">
                        <div class="form-group">
                            <label asp-for="CPF" class="control-label"></label>
                            <input asp-for="CPF" class="form-control form-control-lg cpf" />
                            <span asp-validation-for="CPF" class="text-danger"></span>
                        </div>
                    </div>

                    <div class="campos">
                        <div class="form-group">
                            <label asp-for="Telefone" class="control-label"></label>
                            <input asp-for="Telefone" class="form-control form-control-lg telefone" />
                            <span asp-validation-for="Telefone" class="text-danger"></span>
                        </div>
                    </div>

                    <div class="campos">
                        <div class="form-group">
                            <label asp-for="NomeUsuario" class="control-label">Nome de usuário</label>
                            <input asp-for="NomeUsuario" class="form-control form-control-lg" />
                            <span asp-validation-for="NomeUsuario" class="text-danger"></span>
                        </div>
                    </div>

                    <div class="campos">
                        <div class="form-group">
                            <label asp-for="Email" class="control-label"></label>
                            <input asp-for="Email" type="email" class="form-control form-control-lg" />
                            <span asp-validation-for="Email" class="text-danger"></span>
                        </div>
                    </div>

                    <div class="form-group botoes">
                        <input type="submit" value="Atualizar" class="btn btn-outline-info btn-lg" /> &nbsp;
                        <a asp-action="Index" asp-controller="Usuarios" class="btn btn-link btn-lg">Voltar</a>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}

    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.maskedinput/1.4.1/jquery.maskedinput.min.js"></script>

    <script>
        $(function () {
            $(".cpf").mask("999.999.999-99");
            $(".telefone").mask("(99) 9 9999-9999");
        })
    </script>
}

AluguelCarro/Views/Usuarios/Index.cshtml
@model AluguelCarro.Models.Usuario
@{
    ViewData["Title"] = "Meus dados";
}

<div class="dados">
    <div class="card">
        <div class="card-header">
            <h3 class="titulo">
                <i class="fas fa-address-card fa-lg"></i> &nbsp; Meus dados &nbsp;
                <a asp-action="Atualizar" asp-controller="Usuarios" asp-route-UsuarioId="@Model.Id" class="btn btn-outline-secondary" data-toggle="tooltip" data-placement="right" title="Atualizar dados"><i class="far fa-edit fa-lg"></i></a>
            </h3>
        </div>
        <div class="card-body">
            <div class="input-group col-8 campos">
                <div class="input-group-prepend">
                    <span class="input-group-text"><i class="fas fa-signature fa-lg"></i></span>
                </div>
                <input asp-for="Nome" type="text" class="form-control form-control-lg" readonly />
            </div>

            <div class="input-group col-8 campos">
                <div class="input-group-prepend">
                    <span class="input-group-text"><i class="far fa-address-card fa-lg"></i></span>
                </div>
                <input asp-for="CPF" type="text" class="form-control form-control-lg" readonly />
            </div>

            <div class="input-group col-8 campos">
                <div class="input-group-prepend">
                    <span class="input-group-text"><i class="fas fa-phone-square fa-lg"></i></span>
                </div>
                <input asp-for="Telefone" type="text" class="form-control form-control-lg" readonly />
            </div>

            <div class="input-group col-8 campos">
                <div class="input-group-prepend">
                    <span class="input-group-text"><i class="far fa-envelope fa-lg"></i></span>
                </div>
                <input asp-for="Email" type="text" class="form-control form-control-lg" readonly />
            </div>
        </div>

    </div>
</div>


<div class="enderecos">
    <div class="card">
        <div class="card-header">
            <h3 class="titulo">
                <i class="fas fa-home fa-lg"></i> &nbsp; Meus endereços &nbsp;
                <a asp-action="Create" asp-controller="Enderecos" class="btn btn-outline-secondary" data-toggle="tooltip" data-placement="right" title="Novo endereço"><i class="fas fa-plus-circle fa-lg"></i></a>
            </h3>
        </div>
        <div class="card-body">
            @await Component.InvokeAsync("Endereco")
        </div>

    </div>
</div>

<div class="carros">
    <div class="card">
        <div class="card-header">
            <h3 class="titulo">
                <i class="fas fa-car fa-lg"></i> &nbsp; Meus carros alugados &nbsp;
            </h3>
        </div>
        <div class="card-body">
            @await Component.InvokeAsync("CarrosAlugados")
        </div>

    </div>
</div>

<partial name="_ModalExclusao" />

@section Scripts{
    <script>
        $(function () {
            $('[data-toggle="tooltip"]').tooltip();
        })
        function ConfirmarExclusao(id, nome, controller) {
            $(".Nome").html(nome);
            $(".modal").modal("show");
            $(".btnExcluir").on('click', function () {
                var url = "/" + controller + "/Delete/";
                $.ajax({
                    method: "POST",
                    url: url,
                    data: { id: id },
                    success: function () {
                        alert("Registro excluído");
                        location.reload();
                    }
                })
            })
        }
    </script>
}

AluguelCarro/Views/Usuarios/Login.cshtml
@model AluguelCarro.Models.ViewModels.LoginViewModel
@{
    ViewData["Title"] = "Efetuar login de usuário";
}

<div class="border border-light rounded shadow col-md-8">
    <div class="container">
        <h3 class="titulo"><i class="fas fa-user"></i>Efetuar login de usuário</h3>
        <hr />
        <div class="row">
            <div class="col-md-8">
                <form asp-action="Login">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>

                    <div class="campos">
                        <div class="form-group">
                            <label asp-for="Email" class="control-label">Email</label>
                            <input asp-for="Email" type="email" class="form-control form-control-lg" />
                            <span asp-validation-for="Email" class="text-danger"></span>
                        </div>
                    </div>

                    <div class="campos">
                        <div class="form-group">
                            <label asp-for="Senha" class="control-label">Senha</label>
                            <input asp-for="Senha" class="form-control form-control-lg" />
                            <span asp-validation-for="Senha" class="text-danger"></span>
                        </div>
                    </div>

                    <div class="form-group botoes">
                        <input type="submit" value="Efetuar Login" class="btn btn-outline-info btn-lg" /> &nbsp;
                        <a asp-action="Registro" asp-controller="Usuarios" class="btn btn-link btn-lg">Não sou registrado</a>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

AluguelCarro/Views/Usuarios/Registro.cshtml
@model AluguelCarro.Models.ViewModels.RegistroViewModel
@{
    ViewData["Title"] = "Registro de novos usuários";
}

<div class="border border-light rounded shadow col-md-8">
    <div class="container">
        <h3 class="titulo"><i class="fas fa-user"></i>Registro de novos usuários</h3>
        <hr />
        <div class="row">
            <div class="col-md-8">
                <form asp-action="Registro">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>

                    <div class="campos">
                        <div class="form-group">
                            <label asp-for="Nome" class="control-label">Nome</label>
                            <input asp-for="Nome" class="form-control form-control-lg" />
                            <span asp-validation-for="Nome" class="text-danger"></span>
                        </div>
                    </div>

                    <div class="campos">
                        <div class="form-group">
                            <label asp-for="CPF" class="control-label"></label>
                            <input asp-for="CPF" class="form-control form-control-lg cpf" />
                            <span asp-validation-for="CPF" class="text-danger"></span>
                        </div>
                    </div>

                    <div class="campos">
                        <div class="form-group">
                            <label asp-for="Telefone" class="control-label"></label>
                            <input asp-for="Telefone" class="form-control form-control-lg telefone" />
                            <span asp-validation-for="Telefone" class="text-danger"></span>
                        </div>
                    </div>

                    <div class="campos">
                        <div class="form-group">
                            <label asp-for="NomeUsuario" class="control-label">Nome de usuário</label>
                            <input asp-for="NomeUsuario" class="form-control form-control-lg" />
                            <span asp-validation-for="NomeUsuario" class="text-danger"></span>
                        </div>
                    </div>

                    <div class="campos">
                        <div class="form-group">
                            <label asp-for="Email" class="control-label"></label>
                            <input asp-for="Email" type="email" class="form-control form-control-lg" />
                            <span asp-validation-for="Email" class="text-danger"></span>
                        </div>
                    </div>

                    <div class="campos">
                        <div class="form-group">
                            <label asp-for="Senha" class="control-label"></label>
                            <input asp-for="Senha" type="password" class="form-control form-control-lg" />
                            <span asp-validation-for="Senha" class="text-danger"></span>
                        </div>
                    </div>


                    <div class="form-group botoes">
                        <input type="submit" value="Salvar" class="btn btn-outline-success btn-lg" /> &nbsp;
                        <a asp-action="Login" asp-controller="Usuarios" class="btn btn-link btn-lg">Já sou registrado</a>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}

    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.maskedinput/1.4.1/jquery.maskedinput.min.js"></script>

    <script>
        $(function () {
            $(".cpf").mask("999.999.999-99");
            $(".telefone").mask("(99) 9 9999-9999");
        })
    </script>
}