AluguelCarro/Models/Carro.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace AluguelCarro.Models
{
    public class Carro
    {
        public int CarroId { get; set; }
        public string Nome { get; set; }
        public string Marca { get; set; }
        public String Foto { get; set; }
        public int PrecoDiaria { get; set; }
        public ICollection<Aluguel> Alugueis { get; set; }
    }
}

AluguelCarro/Controllers/AlugueisController.cs
using AluguelCarro.AcessoDados.Interfaces;
using AluguelCarro.Models;
using AluguelCarro.Models.ViewModels;
using AluguelCarro.Servicos;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace AluguelCarro.Controllers
{
    [Authorize]
    public class AlugueisController : Controller
    {
        private readonly IUsuarioRepositorio _usuarioRepositorio;
        private readonly IContaRepositorio _contaRepositorio;
        private readonly IAluguelRepositorio _aluguelRepositorio;
        private readonly ILogger<AlugueisController> _logger;
        private readonly IEmail _email;
        public AlugueisController(IUsuarioRepositorio usuarioRepositorio, IContaRepositorio contaRepositorio, IAluguelRepositorio aluguelRepositorio, ILogger<AlugueisController> logger, IEmail email)
        {
            _usuarioRepositorio = usuarioRepositorio;
            _contaRepositorio = contaRepositorio;
            _aluguelRepositorio = aluguelRepositorio;
            _logger = logger;
            _email = email;
        }
        public IActionResult Alugar(int carroId, int precoDiaria)
        {
            _logger.LogInformation("Começando o aluguel do carro");

            var aluguel = new AluguelViewModel
            {
                CarroId = carroId,
                PrecoDiaria = precoDiaria
            };
            return View(aluguel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Alugar(AluguelViewModel aluguel)
        {
            if (ModelState.IsValid)
            {
                var usuario = await _usuarioRepositorio.PegarUsuarioLogado(User);
                var saldo =  _contaRepositorio.PegarSaldoPeloId(usuario.Id);

                if (await _aluguelRepositorio.VerificarReserva(usuario.Id, aluguel.CarroId, aluguel.Inicio, aluguel.Fim))
                {
                    _logger.LogInformation("Usuário já possui essa reserva");
                    TempData["Aviso"] = "Você já possui essa reserva";
                    return View(aluguel);
                }
                else if(aluguel.PrecoTotal > saldo)
                {
                    _logger.LogInformation("Saldo insuficiente");
                    TempData["Aviso"] = "Saldo insuficiente";
                    return View(aluguel);
                }
                else
                {
                    Aluguel a = new Aluguel
                    {
                        UsuarioId = usuario.Id,
                        CarroId = aluguel.CarroId,
                        Inicio = aluguel.Inicio,
                        Fim = aluguel.Fim,
                        PrecoTotal = aluguel.PrecoTotal
                    };

                    _logger.LogInformation("Enviando e-mail com detalhes da reserva");
                    string assunto = "reserva concluida com sucesso";

                    string mensagem = string.Format("Seu veículo já o aguarda. Você podera pega-lo dia {0}" +
                        " e devara deveolve-lo dia {1}. o preço será de R${2},00. Divirta-se!!!", aluguel.Inicio, aluguel.Fim, aluguel.PrecoTotal);

                    await _email.EnviarEmail(usuario.Email, assunto, mensagem);

                    await _aluguelRepositorio.Inserir(a);
                    _logger.LogInformation("Reserva feita");

                    _logger.LogInformation("Atualizando saldo usuario");
                    var saldoUsuario = await _contaRepositorio.PegarSaldoPeloUsuarioId(usuario.Id);
                    saldoUsuario.Saldo = saldoUsuario.Saldo - aluguel.PrecoTotal;
                    await _contaRepositorio.Atualizar(saldoUsuario);
                    _logger.LogInformation("Saldo Atualizado");


                    return RedirectToAction("index", "Carros");
                }
            }
            _logger.LogInformation("Informações inválidas");
            return View(aluguel);

        }
    }
}

AluguelCarro/Controllers/CarrosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using AluguelCarro.Models;
using AluguelCarro.AcessoDados.Interfaces;
using Microsoft.AspNetCore.Hosting;
using Microsoft.Extensions.Logging;
using Microsoft.AspNetCore.Http;
using System.IO;
using Microsoft.AspNetCore.Authorization;

namespace AluguelCarro.Controllers
{
    [Authorize]
    public class CarrosController : Controller
    {
        private readonly ICarroRepositorio _carroRepositorio;
        private readonly IHostingEnvironment _hostingEnvironment;
        private readonly ILogger<CarrosController> _logger;

        public CarrosController(ICarroRepositorio carroRepositorio, IHostingEnvironment hostingEnvironment, ILogger<CarrosController> logger)
        {
            _carroRepositorio = carroRepositorio;
            _hostingEnvironment = hostingEnvironment;
            _logger = logger;
        }

        public async Task<IActionResult> Index()
        {
            _logger.LogInformation("Listando todos os carros");
            return View(await _carroRepositorio.PegarTodos().ToListAsync());
        }


        public IActionResult Create()
        {
            _logger.LogInformation("Novo carro");
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("CarroId,Nome,Marca,Foto,PrecoDiaria")] Carro carro, IFormFile arquivo)
        {
            if (ModelState.IsValid)
            {
                if (arquivo != null)
                {
                    _logger.LogInformation("Criando link da pasta");
                    var linkUpload = Path.Combine(_hostingEnvironment.WebRootPath, "Imagens");

                    using (FileStream fileStream = new FileStream(Path.Combine(linkUpload, arquivo.FileName), FileMode.Create))
                    {
                        _logger.LogInformation("Copiando arquivo para pasta");
                        await arquivo.CopyToAsync(fileStream);
                        _logger.LogInformation("Arquivo copiado");
                        carro.Foto = "~/Imagens/" + arquivo.FileName;
                    }
                }
                _logger.LogInformation("Salvando novo carro");

                await _carroRepositorio.Inserir(carro);
                return RedirectToAction(nameof(Index));
            }
            _logger.LogError("Informações inválidas");
            return View(carro);
        }

        public async Task<IActionResult> Edit(int id)
        {

            _logger.LogInformation("Atualizar carro");

            var carro = await _carroRepositorio.PegarPeloId(id);
            if (carro == null)
            {
                _logger.LogError("Carro não encontrado");
                return NotFound();
            }

            TempData["FotoCarro"] = carro.Foto;

            return View(carro);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("CarroId,Nome,Marca,Foto,PrecoDiaria")] Carro carro, IFormFile arquivo)
        {
            if (id != carro.CarroId)
            {
                _logger.LogError("Carro não encontrado");
                return NotFound();
            }
            carro.Foto = TempData["FotoCarro"].ToString();
            if (ModelState.IsValid)
            {
                if (arquivo != null)
                {
                    _logger.LogInformation("Criando link da pasta");
                    var linkUpload = Path.Combine(_hostingEnvironment.WebRootPath, "Imagens");

                    using (FileStream fileStream = new FileStream(Path.Combine(linkUpload, arquivo.FileName), FileMode.Create))
                    {
                        _logger.LogInformation("Copiando arquivo para pasta");
                        await arquivo.CopyToAsync(fileStream);
                        _logger.LogInformation("Arquivo copiado");
                        carro.Foto = "~/Imagens/" + arquivo.FileName;
                    }
                }

                else carro.Foto = TempData["FotoCarro"].ToString();

                _logger.LogInformation("Atualizando carro");
                await _carroRepositorio.Atualizar(carro);
                return RedirectToAction(nameof(Index));
            }
            return View(carro);
        }

        [HttpPost]
        public async Task<JsonResult> Delete(int id)
        {
            var carro = await _carroRepositorio.PegarPeloId(id);
            string fotoCarro = carro.Foto;
            fotoCarro = fotoCarro.Replace("~", "wwwroot");
            System.IO.File.Delete(fotoCarro);

            _logger.LogInformation("Excluindo carro");
            await _carroRepositorio.Excluir(id);
            return Json("Carro excluído");
        }
    }
}

AluguelCarro/Views/Carros/Create.cshtml
@model AluguelCarro.Models.Carro

@{
    ViewData["Title"] = "Novo carro";
}

<div class="border border-light rounded shadow col-md-8">
    <div class="container">
        <h3 class="titulo"><i class="fas fa-car fa-lg"></i>Novo carro</h3>
        <hr />
        <div class="row">
            <div class="col-md-8">
                <form asp-action="Create" enctype="multipart/form-data">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>

                    <div class="row">
                        <div class="col-6">
                            <div class="campos">
                                <div class="form-group">
                                    <label asp-for="Nome" class="control-label"></label>
                                    <input asp-for="Nome" class="form-control form-control-lg" />
                                    <span asp-validation-for="Nome" class="text-danger"></span>
                                </div>
                            </div>

                            <div class="campos">
                                <div class="form-group">
                                    <label asp-for="Marca" class="control-label"></label>
                                    <input asp-for="Marca" class="form-control form-control-lg" />
                                    <span asp-validation-for="Marca" class="text-danger"></span>
                                </div>
                            </div>

                            <div class="campos">
                                <div class="form-group">
                                    <label asp-for="PrecoDiaria" class="control-label"></label>
                                    <input asp-for="PrecoDiaria" class="form-control form-control-lg" />
                                    <span asp-validation-for="PrecoDiaria" class="text-danger"></span>
                                </div>
                            </div>
                        </div>

                        <div class="col-6">
                            <div class="form-group campos">
                                <img src="#" name="arquivo" id="arquivo" height="300" width="300" class="border border-secondary rounded" />
                            </div>
                            <div class="campos">
                                <div class="form-group">
                                    <label asp-for="Foto" class="control-label"></label>
                                    <input asp-for="Foto" type="file" class="form-control-file form-control-lg" name="arquivo" id="arquivo" onchange="CarregarImagem(this)" />
                                    <span asp-validation-for="Foto" class="text-danger"></span>
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="form-group botoes">
                        <input type="submit" value="Salvar" class="btn btn-outline-success btn-lg" /> &nbsp;
                        <a asp-action="Index" class="btn btn-link btn-lg">Voltar</a>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}

    <script>
        function CarregarImagem(input) {
            if (input.files && input.files[0]) {
                var reader = new FileReader();
                reader.onload = function (e) {
                    $("#arquivo").attr('src', e.target.result).width(300).height(300);
                }
            }
            reader.readAsDataURL(input.files[0]);
        }
    </script>
}

AluguelCarro/Views/Carros/Edit.cshtml
@model AluguelCarro.Models.Carro

@{
    ViewData["Title"] = "Edit";
}

<div class="border border-light rounded shadow col-md-8">
    <div class="container">
        <h3 class="titulo"><i class="fas fa-car fa-lg"></i>Atualizar carro @Model.Nome</h3>
        <hr />
        <div class="row">
            <div class="col-md-8">
                <form asp-action="Edit" enctype="multipart/form-data">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <input type="hidden" asp-for="CarroId" />
                    <div class="row">
                        <div class="col-6">
                            <div class="campos">
                                <div class="form-group">
                                    <label asp-for="Nome" class="control-label"></label>
                                    <input asp-for="Nome" class="form-control form-control-lg" />
                                    <span asp-validation-for="Nome" class="text-danger"></span>
                                </div>
                            </div>

                            <div class="campos">
                                <div class="form-group">
                                    <label asp-for="Marca" class="control-label"></label>
                                    <input asp-for="Marca" class="form-control form-control-lg" />
                                    <span asp-validation-for="Marca" class="text-danger"></span>
                                </div>
                            </div>

                            <div class="campos">
                                <div class="form-group">
                                    <label asp-for="PrecoDiaria" class="control-label"></label>
                                    <input asp-for="PrecoDiaria" class="form-control form-control-lg" />
                                    <span asp-validation-for="PrecoDiaria" class="text-danger"></span>
                                </div>
                            </div>
                        </div>

                        <div class="col-6">
                            <div class="form-group campos">
                                @if (Model.Foto != null)
                                {
                                    <img src="@Url.Content(Model.Foto)" name="arquivo" id="arquivo" height="300" width="300" class="border border-secondary rounded" />
                                }
                                else
                                {
                                    <img src="#" name="arquivo" id="arquivo" height="300" width="300" class="border border-secondary rounded" />
                                }
                            </div>
                            <div class="campos">
                                <div class="form-group">
                                    <label asp-for="Foto" class="control-label"></label>
                                    <input asp-for="Foto" type="file" class="form-control-file form-control-lg" name="arquivo" id="arquivo" onchange="CarregarImagem(this)" />
                                    <span asp-validation-for="Foto" class="text-danger"></span>
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="form-group botoes">
                        <input type="submit" value="Atualizar" class="btn btn-outline-info btn-lg" /> &nbsp;
                        <a asp-action="Index" class="btn btn-link btn-lg">Voltar</a>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}

    <script>
        function CarregarImagem(input) {
            if (input.files && input.files[0]) {
                var reader = new FileReader();
                reader.onload = function (e) {
                    $("#arquivo").attr('src', e.target.result).width(300).height(300);
                }
            }
            reader.readAsDataURL(input.files[0]);
        }
    </script>
}

AluguelCarro/Views/Carros/Index.cshtml
@model IEnumerable<AluguelCarro.Models.Carro>

@{
    ViewData["Title"] = "Carros cadastrados";

    var controller = "Carros";
}

@if (User.IsInRole("Administrador"))
{
    <h3 class="titulos">
        <i class="fas fa-car fa-lg"></i> Carros Cadastrados &nbsp;
        <a asp-action="Create" asp-controller="Carros" class="btn btn-outline-secondary btn-lg" data-toggle="tooltip" data-placement="right" title="Novo carro">
            <i class="fas fa-plus-circle"></i>
        </a>
    </h3>

}
else
{
    <h3 class="titulos">
        <i class="fas fa-car fa-lg"></i> Carros disponíveis &nbsp;
    </h3>

}

<div class="row">

    @foreach (var item in Model)
    {
        <div class="col-4">
            <div class="cartoes">
                <div class="card">
                    <img src="@Url.Content(item.Foto)" class="card-img-top img-fluid" />
                    <div class="card-body">
                        <h5 class="card-title">@item.Marca - @item.Nome</h5>
                        <h5><span class="badge badge-secondary">R$ @item.PrecoDiaria,00</span></h5>
                    </div>
                    <div class="card-footer">
                        @if (User.IsInRole("Administrador"))
                        {
                            <a asp-action="Edit" asp-controller="Carros" asp-route-id="@item.CarroId" class="btn btn-outline-info">Atualizar</a>
                            <a onclick="ConfirmarExclusao(@item.CarroId, '@item.Nome', '@controller')" class="btn btn-outline-danger">Excluir</a>
                        }
                        else
                        {
                            <a asp-action="Alugar" asp-controller="Alugueis" asp-route-CarroId="@item.CarroId" asp-route-PrecoDiaria="@item.PrecoDiaria" class="btn btn-outline-info btn-block">Alugar veículo</a>
                        }
                    </div>
                </div>
            </div>
        </div>
    }
</div>

<partial name="_ModalExclusao" />

@section Scripts
    {
    <script>
        $(function () {
            $('[data-toggle="tooltip"]').tooltip();
        })

        function ConfirmarExclusao(id, nome, controller) {
            $(".Nome").html(nome);
            $(".modal").modal("show");
            $(".btnExcluir").on('click', function () {
                var url = "/" + controller + "/Delete/";

                $.ajax({
                    method: "POST",
                    url: url,
                    data: { id: id },
                    success: function () {
                        alert("Registro excluído");
                        location.reload();
                    }
                })
            })
        }
    </script>

}